# author: samuel verneck
# contact: osamucaaaa@gmail.com
# version: 0.0.1

# script de instalação automatizada de programas windows para meu ambiente de trabalho e uso diário.

- name: "Chocolatey"
  hosts: windows
  tasks:
    - name: Install chocolatey
      win_chocolatey:
        name:
          - chocolatey
          - chocolatey-core.extension
        state: present

- name: "Google Chrome"
  hosts: windows
  tasks:
    - name: Install Google Chrome
      win_chocolatey:
          name: googlechrome
          state: present
          ignore_checksums: yes

- name: Ensure 7-Zip is installed via Chocolatey
  win_chocolatey:
    name: 7zip
    state: present

- name: VSCode installed
  win_chocolatey:
    name: vscode
    state: present
